# clone directory
clone_folder: c:\projects\pvr.hdhomerun

# fetch repository as zip archive
#shallow_clone: true                 # default is "false"

environment:
  ADDON: pvr.hdhomerun
  CONFIG: Release

  matrix:
    - CMAKE_GENERATOR: Visual Studio 12 2013
    - CMAKE_GENERATOR: Visual Studio 12 2013 Win64
    - CMAKE_GENERATOR: Visual Studio 14 2015
    - CMAKE_GENERATOR: Visual Studio 14 2015 Win64

build_script:
  - cmake --version
  - cd c:\projects
  - set ROOT=%cd%
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd %ADDON%
  - mkdir build
  - cd build
  # Must use absolute path for cmake to build depends correctly
  - cmake -G "%CMAKE_GENERATOR%" -DADDONS_TO_BUILD=%ADDON% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=%ROOT% -DCMAKE_INSTALL_PREFIX=%ROOT%\xbmc\addons -DCMAKE_USER_MAKE_RULES_OVERRIDE=%ROOT%\xbmc\cmake\scripts\windows\CFlagOverrides.cmake -DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX=%ROOT%\xbmc\cmake\scripts\windows\CXXFlagOverrides.cmake -DPACKAGE_ZIP=1 %ROOT%\xbmc\cmake\addons
  - cmake --build . --config %CONFIG%
