version: BuildNr.{build}

init:
- ps: $commit = $env:appveyor_repo_commit.SubString(0,7)
- ps: $timestamp = $env:appveyor_repo_commit_timestamp.SubString(0,10)
- ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch, $commit, $timestamp)

# clone directory
clone_folder: c:\projects\pvr.hdhomerun

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

environment:
  ADDON: pvr.hdhomerun

# Operating system (build VM template)
os: Visual Studio 2015

platform: 
  - Win32
  - x64

configuration:
  - Debug
  - Release
  
build_script:
  - cd ..
  - set ROOT=%cd%
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd %ADDON%
  - mkdir build
  - cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  # Must use absolute path for cmake to build depends correctly
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DADDONS_TO_BUILD=%ADDON% -DCMAKE_BUILD_TYPE=%configuration% -DADDON_SRC_PREFIX=%ROOT% -DCMAKE_INSTALL_PREFIX=%ROOT%\xbmc\addons -DCMAKE_USER_MAKE_RULES_OVERRIDE=%ROOT%\xbmc\cmake\scripts\windows\CFlagOverrides.cmake -DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX=%ROOT%\xbmc\cmake\scripts\windows\CXXFlagOverrides.cmake -DPACKAGE_ZIP=1 %ROOT%\xbmc\cmake\addons
  - cmake --build . --config %configuration%
